# Generated by Django 5.1.6 on 2025-02-27 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tradeanalytics',
            name='trading_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
