# Generated by Django 5.1.6 on 2025-02-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.transaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
