# Generated by Django 5.1.6 on 2025-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calorie',
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
