# Generated by Django 5.1.6 on 2025-02-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_calories_food_calorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calorie',
            new_name='calories',
        ),
    ]
