# Generated by Django 5.1.6 on 2025-02-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_calorie_food_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calories',
            new_name='calorie',
        ),
    ]
