# Generated by Django 5.1.6 on 2025-02-25 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='buy_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.buyorder'),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.buyorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sell_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.sellorder'),
        ),
    ]
